version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: openpg
      POSTGRES_PASSWORD: openpgpwd
      POSTGRES_DB: zhap_parser_test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://openpg:openpgpwd@db:5432/zhap_parser_test
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  pgdata:
