name: Input Id

on:
  workflow_dispatch:
    inputs:
      work_id:
        description: 'Define Work Id'
        required: true      
        default: None
jobs:
  use-inputs:
    runs-on: ubuntu-latest

    env:
      ENV_WORK: ${{ github.event.inputs.work_id }}

    steps:
      - name: Checking Env Values
        run: |
          echo "Environment: $ENV_WORK"

      - name: Env log
        run: |
          echo "You could now use $ENV_WORK to trigger environment-specific tasks."