name: PR Check Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Print PR info
          run: |
                echo "Repository: ${{ github.repository }}"
                echo "PR Number: ${{ github.event.pull_request.number }}"
                echo "Base branch: ${{ github.base_ref }}"
                echo "Head branch: ${{ github.head_ref }}"
        - name: Run Python
          run: |
            if [ "${{ github.base_ref }}" != "main" ]; then
                echo " PR To ${{github.head_ref}} Ignoring execution"
                exit 0
            else 
                echo " PR To ${{github.head_ref}} Starting execution"
                python app.py
                exit 1
            fi
        