name: PR Check Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-pr:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: github
          POSTGRES_PASSWORD: github
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U github -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print PR info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Base branch: ${{ github.base_ref }}"
          echo "Head branch: ${{ github.head_ref }}"

      - name: Run Python
        env:
          DATABASE_URL: postgresql://github:github@localhost:5432/test_db
        run: |
          if [ "${{ github.base_ref }}" != "main" ]; then
              echo " PR To ${{github.head_ref}} Ignoring execution"
              exit 0
          else 
              echo " PR To ${{github.head_ref}} Starting execution"
              python app.py
          fi
